### ISSUE TITLE
A paid user can create a company

### ISSUE THREAD

**Issue by suuunly** [flowcore-io/open-source-conference-app#10]
**Is your feature request related to a problem? Please describe.** 👨‍🏫
Given that you wish to associate users with companies, this should be implemented as a feature.

**Describe the solution you'd like** 📝
- only active users* for the current event must be able to create a company
  - when creating one, they must fill out the following info
    - linkedin url
    - avatar
    - name
    - description
    - website
- the owner must be able to transfer ownership to a current employee (an employee is a user that has been added to the company)
- a user can select what company they work for on their profile
  - the company owner, will receive a notification that they have joined

- admins must be able to change owner of a company
- admins must be able to remove and add users to a company

**Additional context**
An active users, could be anyone who has purchased tickets and/or claimed a ticket.

**Comment by odinellefsen** [comment]
Isn't every user an active user because you're only able to access the conference if you have purchased ticket/s and/or claimed a ticket?
