### ISSUE TITLE
Convert the app to a PWA

### ISSUE THREAD

**Issue by suuunly** [flowcore-io/open-source-conference-app#12]
**Is your feature request related to a problem? Please describe.** 👨‍🏫
People prefer an app experience over a "website"

**Describe the solution you'd like** 📝
Therefore the app should be converted to a PWA

**Additional context**
https://medium.com/readytowork-org/implementing-pwa-in-the-next-13-application-3e46f6b3f6d8

**Comment by olavurellefsen** [comment]
Resolved with #14
