### ISSUE TITLE
Use Flowcore CLI to create Data Core, Flow Type and Event Type configuration

### ISSUE THREAD

**Issue by jbiskur** [flowcore-io/open-source-conference-app#13]
**Is your feature request related to a problem? Please describe.** 👨‍🏫
When creating a new deployment or developing locally it should be easy to create a self-contained data-core structure up with the flowcore cli 

**Describe the solution you'd like** 📝
Create a manifest that describes any Flowcore Resources required for storing the data for the conference app
Use the flowcore cli's data-core apply functionality to apply the manifest to your setup

**Comment by suuunly** [comment]
This has been resolved, so I am closing this issue
