### ISSUE TITLE
Replace placeholder icon

### ISSUE THREAD

**Issue by suuunly** [flowcore-io/open-source-conference-app#36]
**Is your feature request related to a problem? Please describe.** 👨‍🏫
Currently the app is using a temporary icon/app icon. This should be switched

**Describe the solution you'd like** 📝
These are the icons that it should be replaced with:

The app icon being the following:
![Conference App Icon (circle)](https://github.com/flowcore-io/open-source-conference-app/assets/3743913/fdb3442f-38d3-4913-b587-27562e5baa1b)

The browser icon being the following:
![Conference App Icon (transparent)](https://github.com/flowcore-io/open-source-conference-app/assets/3743913/418eb712-1a88-4186-9b9f-7781d88cfb48)

**Additional context**
The app icon will require that we generate multiple icon resolutions. Looking at the existing placeholder icon should help.

The browser icon might require that the file is converted to an `.ico` file first

__Here is an upscaled version of one of the images:__
![AI Image Upscaler](https://github.com/flowcore-io/open-source-conference-app/assets/3743913/d7bd0b35-604e-4950-a31a-f575b8ddca9f)

**Comment by pojith** [comment]
.take

**Comment by pojith** [comment]
I required few information about icon folder 
where is located its my first contribution

**Comment by suuunly** [comment]
Hello @pojith, you can find the icons and images in the `public` folder :)
In that folder you will find the following files: `img-192.png`, `img-384.png`, `img-512.png`, and the `favicon.ico`

As shown here:
<img width="488" alt="image" src="https://github.com/flowcore-io/open-source-conference-app/assets/3743913/09622faf-e64d-404e-a2c2-6da94d2574f2">

These 4 files need to be replaced with the images mentioned in the original post 😄
This will require that you downsize the:
1. img files to fit the specific resolutions (192x192, 384x384, 512x512).
2. generate an `.ico` file for the `favicon.ico`

You can use one of the million of online generators 😄

**Comment by pojith** [comment]
thanks

**Comment by pojith** [comment]
i have doubt  where original post is located 
can u help me

**Comment by pojith** [comment]
ok

**Comment by pojith** [comment]
can u check pull request

**Comment by pojith** [comment]
can u check pull request again

**Comment by pojith** [comment]
i sorry for taking long time for solving simple problem

**Comment by SriHarshaMittapalli** [comment]
Hello @suuunly,

Could you please help me with how to run this application? I have forked the project locally but am unable to run the application.

**Comment by suuunly** [comment]
> i sorry for taking long time for solving simple problem

No worries. ❤ I will look over the PR in the morning 😁

**Comment by pojith** [comment]
sir can u check now i tried to resize the image  size but pixel are breaking

**Comment by suuunly** [comment]
@pojith. Ah, fair enough. Can you it with specifically these 3 images then? 🤔 
See if that helps 😄 

![384x384](https://github.com/flowcore-io/open-source-conference-app/assets/3743913/5a46a37a-caaa-4808-ad1b-eac8726bd34a)
![192x192](https://github.com/flowcore-io/open-source-conference-app/assets/3743913/374d24e0-f7a6-4966-838b-adfd9f291706)
![512x512](https://github.com/flowcore-io/open-source-conference-app/assets/3743913/d2911c59-8ad9-4079-91f6-c7a310f0ed18)

**Comment by pojith** [comment]
ok i will see

**Comment by pojith** [comment]
can u check now

**Comment by pojith** [comment]
sir i want to ask how you resize image without loss of the pixel

**Comment by suuunly** [comment]
This task can now be closed! 👍 
good job! 🥇😄
